
#host (ip o nombre del servidor)
db.hostMysql= 26.210.79.159
db.hostPostgreSQL= 26.170.127.143
db.hostSqlserver= LAPTOP-M02N6LGI
#-----------------------
#users (usuario de acceso)
db.userMysql= uluis
db.userPostgreSQL= luis11
db.userSqlserver= sa
#-----------------------
#password (clave de acceso)
db.passwordMysql= 12345678
db.passwordPostgreSQL= 1234
db.passwordSqlserver= 12345678
#-----------------------
#Mysql - taquilla
#PostgreSql - dulceria_cine
#SQL Server - ProjectionDB
